
version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        freshness: 
          warn_after: 
            count: 90 
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        identifier : raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id
        tests: 
          - unique:   
              column_name: "(orders_id || '-' || pdt_id)" #ici il s'agit de la formulation de la PK : on CONCATENATE 2 colonnes pour avoir une valeur propre pour chaque campaign car il y a des doublons 
        columns:
          - name: date_date
            description: the date of the purchase
          - name: orders_id
            description: the id of the order
          - name: products_id
            description: primary key of the table
          - name: revenue
            description: the amount total of a specific product_id from its sale
          - name: quantity
            description: the quantity of each product_id sold 
      - name: product
        identifier: raw_gz_product
        description: products of greenweez / we have on row per products_id and its purchase_price
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: the price of a product_id
      - name : ship
        identifier : raw_gz_ship
        description: shipping_cost of greenweez / we have one row per orders_id and its own shipping_fee, logcost and ship_cost
        columns:
          - name: orders_id
            description: the id of the order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping_fee of an order_id
          - name: shipping_fee_1
            description: shipping_fee of an order_id
          - name: logCost
            description: cost of logistic
          - name: ship_cost
            description: shipping cost
      - name: adwords
        identifier: raw_gz_adwords
        description: ad
        tests: 
          - unique:   
              column_name: "(date_date || '_' || campaign_key)" #ici il s'agit de la formulation de la PK : on CONCATENATE 2 colonnes pour avoir une valeur propre pour chaque campaign car il y a des doublons 
        columns:
          - name: date_date #je mets uniquet et not null pour chaque colonne des autres tables concernées par la primary key
            tests:
              - unique
              - not_null
          - name: paid_source
          - name: campaign_key #je mets uniquet et not null pour chaque colonne des autres tables concernées par la primary key
            tests:
              - unique
              - not_null
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: bing
        identifier: raw_gz_bing
        description: bing
        columns:
          - name: date_date #je mets uniquet et not null pour chaque colonne des autres tables concernées par la primary key
            tests:
              - unique
              - not_null
          - name: paid_source
          - name: campaign_key #je mets uniquet et not null pour chaque colonne des autres tables concernées par la primary key
            tests:
              - unique
              - not_null
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo
        columns:
          - name: date_date #je mets uniquet et not null pour chaque colonne des autres tables concernées par la primary key
            tests:
              - unique
              - not_null
          - name: paid_source
          - name: campaign_key #je mets uniquet et not null pour chaque colonne des autres tables concernées par la primary key
            tests:
              - unique
              - not_null
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook
        columns:
          - name: date_date #je mets uniquet et not null pour chaque colonne des autres tables concernées par la primary key
            tests:
              - unique
              - not_null
          - name: paid_source
          - name: campaign_key #je mets uniquet et not null pour chaque colonne des autres tables concernées par la primary key
            tests:
              - unique
              - not_null
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
          
        